Rename-Item -Path "французский 2.jpg" -NewName "frantsuzskiy_2.jpg"
Rename-Item -Path "французский.jpg" -NewName "frantsuzskiy.jpg"
Rename-Item -Path "пермский с пастрами.jpg" -NewName "permskiy_s_pastrami.jpg"
Rename-Item -Path "пермский с лососем.jpg" -NewName "permskiy_s_lososem.jpg"
Rename-Item -Path "пермский с беконом.jpg" -NewName "permskiy_s_bekonom.jpg"
Rename-Item -Path "фитнес.jpg" -NewName "fitnes.jpg"
Rename-Item -Path "фитнес 2.jpg" -NewName "fitnes_2.jpg"
Rename-Item -Path "англиийский 2.jpg" -NewName "angliyskiy_2.jpg"
Rename-Item -Path "английский.jpg" -NewName "angliyskiy.jpg" 