Rename-Item -Path "печенье брауни.jpg" -NewName "pechenye_brauni.jpg"
Rename-Item -Path "печенье браун.jpg" -NewName "pechenye_braun.jpg"
Rename-Item -Path "цыпленок табака.jpg" -NewName "cyplenok_tabaka.jpg"
Rename-Item -Path "стейк лосося.jpg" -NewName "steyk_lososya.jpg"
Rename-Item -Path "уха -обрезать водку и крутон.jpg" -NewName "uha_obrezat_vodku_i_kruton.jpg"
Rename-Item -Path "салат с ростбифом.jpg" -NewName "salat_s_rostbifom.jpg"
Rename-Item -Path "салат с подкопченой уткой.jpg" -NewName "salat_s_podkopchenoy_utkoy.jpg"
Rename-Item -Path "салат с морскими гадами.jpg" -NewName "salat_s_morskimi_gadami.jpg"
Rename-Item -Path "салат с лососем.jpg" -NewName "salat_s_lososem.jpg"
Rename-Item -Path "пивной сет.jpg" -NewName "pivnoy_set.jpg"
Rename-Item -Path "морской гребешок с клубникой.jpg" -NewName "morskoy_grebeshek_s_klubnikoy.jpg"
Rename-Item -Path "корюшка жареная.jpg" -NewName "koryushka_zharenaya.jpg"
Rename-Item -Path "закуска из телятины.jpg" -NewName "zakuska_iz_telyatiny.jpg"
Rename-Item -Path "жареные острые креветки.jpg" -NewName "zharenye_ostrye_krevetki.jpg"
Rename-Item -Path "дорадо.jpg" -NewName "dorado.jpg"
Rename-Item -Path "грибной капучино.jpg" -NewName "gribnoy_kapuchino.jpg"
Rename-Item -Path "голяшка барана.jpg" -NewName "golyashka_barana.jpg"
Rename-Item -Path "плато гриль.jpg" -NewName "plato_gril.jpg"
Rename-Item -Path "плато креветок.jpg" -NewName "plato_krevetok.jpg"
Rename-Item -Path "трюфельные конфеты.jpg" -NewName "tryufelnye_konfety.jpg"
Rename-Item -Path "чизкейк.jpg" -NewName "chizkeyk.jpg"
Rename-Item -Path "кукис.jpg" -NewName "kukis.jpg"
Rename-Item -Path "мадлены.jpg" -NewName "madleny.jpg"
Rename-Item -Path "теплый картофельный салат.jpg" -NewName "teplyy_kartofelnyy_salat.jpg"
Rename-Item -Path "овощи на гриле.jpg" -NewName "ovoshchi_na_grile.jpg"
Rename-Item -Path "запеченые шампиньоны.jpg" -NewName "zapechenye_shampinony.jpg"
Rename-Item -Path "филе судака.jpg" -NewName "file_sudaka.jpg"
Rename-Item -Path "картофель жаренный.jpg" -NewName "kartofel_zharenyy.jpg"
Rename-Item -Path "свинной рябчик.jpg" -NewName "svinnoy_ryabchik.jpg"
Rename-Item -Path "оссобуко.jpg" -NewName "ossobuko.jpg"
Rename-Item -Path "томленые телячьи щечки.jpg" -NewName "tomlenye_telyachyi_shchechki.jpg"
Rename-Item -Path "бургер.jpg" -NewName "burger.jpg"
Rename-Item -Path "свинные ребрышки.jpg" -NewName "svinnye_rebryshki.jpg"
Rename-Item -Path "морской чаудер.jpg" -NewName "morskoy_chauder.jpg"
Rename-Item -Path "запеченые мидии.jpg" -NewName "zapechenye_midii.jpg"
Rename-Item -Path "посикунчики.jpg" -NewName "posikunchiki.jpg"
Rename-Item -Path "мидии блю чиз.jpg" -NewName "midii_blyu_chiz.jpg"
Rename-Item -Path "мясной чаудер.jpg" -NewName "myasnoi_chauder.jpg"
Rename-Item -Path "стейк салат.jpg" -NewName "steyk_salat.jpg"
Rename-Item -Path "теплый салат с курицей и беконом.jpg" -NewName "teplyy_salat_s_kuritsey_i_bekonom.jpg"
Rename-Item -Path "греческий.jpg" -NewName "grecheskiy.jpg"
Rename-Item -Path "закуска из щучьей икры.jpg" -NewName "zakuska_iz_shchuchey_ikry.jpg"
Rename-Item -Path "домашнее сало.jpg" -NewName "domashnee_salo.jpg"
Rename-Item -Path "тар тар.jpg" -NewName "tar_tar.jpg"
Rename-Item -Path "вителло тоннато.jpg" -NewName "vitello_tonnato.jpg"
Rename-Item -Path "соленые рыжики.jpg" -NewName "solenye_ryzhiki.jpg"
Rename-Item -Path "сельдь с картофелем.jpg" -NewName "seld_s_kartofelem.jpg"
Rename-Item -Path "Карпаччо из телятины.jpg" -NewName "karpachcho_iz_telyatiny.jpg"
Rename-Item -Path "Яблочный лосось слабой соли.jpg" -NewName "yablochnyi_losos_slaboy_soli.jpg" 